name: Security audit

on:
  push
  pull_request
  schedule:
    - cron: '*/30 * * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@alpha
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

