name: Security audit

on:
  schedule:
    - cron: '*/15 * * * *'
  push:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@alpha
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

