# We could use `@actions-rs/cargo` Action ability to automatically install `cross` tool
# in order to compile our application for some unusual targets.

on: [push, pull_request]

name: Cross-compile

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - armv7-unknown-linux-gnueabihf
          - powerpc64-unknown-linux-gnu
          -
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}

  cross-ios-build:
    runs-on: macos-latest
    strategy:
      matrix:
        rust_target:
          - aarch64-apple-ios
          - armv7-apple-ios
          - armv7s-apple-ios
          - i386-apple-ios
          - x86_64-apple-ios
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust ${{ matrix.rust_toolchain }}
        uses: actions-rs/toolchain@master
        with:
            toolchain: stable
            target: ${{ matrix.rust_target }}
            default: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target=${{ matrix.rust_target }}
